#/run/verbose 1
#/event/verbose 1
#/tracking/verbose 1

/sim/setReferencePhysList FTFP_BERT
/sim/seedWithTime
/sim/setFileName out_vis.root

/run/initialize

/sim/exitVol plugSkinBackOut # or larDead
/sim/debug

/gun/particle pi+
/gun/momentumAmp 200 MeV
/gun/direction -1 0 0
/gun/position 0.1 0 0 mm

/vis/open OGL 600x600-0+0
/vis/viewer/set/autoRefresh false
/vis/drawVolume

# /vis/viewer/set/viewpointVector -1 0 0
# /vis/viewer/set/lightsVector -1 -1 -1
#/vis/viewer/set/style wireframe
#/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

#/vis/scene/add/axes 0 0 0 6 cm
/vis/scene/add/trajectories smooth

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2

/vis/scene/endOfEventAction accumulate 0

/vis/geometry/set/visibility World 0 false

#/vis/viewer/set/style surface
#/vis/viewer/set/hiddenMarker true
#/vis/viewer/set/viewpointThetaPhi 120 150
/vis/viewer/set/autoRefresh true

/run/beamOn 1
